### PR TITLE
Create the Subsystem Manager

### PR DESCRIPTION
**Pull request by drvladb**
The Subsystem manager will work to extend the `SmartSubsystem` life cycle methods with actual uses.

### CODE REVIEW

**Review by KevinH45 — DISMISSED** [review]
lgtm
check discord

**Comment by DaBear57** [comment]
is there a reason the enabled looper isn't started in autonomousinit?

**Comment by drvladb** [comment]
> is there a reason the enabled looper isn't started in autonomousinit?

Hmm, good catch. Fixed!

**Review by KevinH45 — APPROVED** [review]
LGTM BRO

**Pull request merged**
