### PR TITLE
Create the missing subsystems using theoretical projects

### PR DESCRIPTION
**Pull request by drvladb**
Included is code that should work with the future subsystems on the robot (commands not included) - values may still need to be tunned. The following subsystems are included:

1. Drivetrain
2. Arm
3. Claw
4. Pneumatics (overarching)

### CODE REVIEW

**Comment by KevinH45** [comment]
Fix your format violations smh

**Comment by drvladb** [comment]
> Fix your format violations smh

Uhhh... NO!

**Comment by KevinH45** [comment]
on Saturday, test drivetrain and fix the error where the two left-side motors are working against each other.

**Review by KevinH45 — CHANGES_REQUESTED** [review]
fix the drivetrain error here as well

**Comment by drvladb** [comment]
Commit the motor fix

**Review by KevinH45 — APPROVED** [review]

**Pull request merged**
